/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ec.edu.monster.view;

import ec.edu.monster.service.FacturaService;
import org.apache.hc.core5.http.ParseException;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.io.IOException;
import java.util.List;

public class Factura extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Factura.class.getName());

    private JTextField txtCedula;
    private JButton btnBuscar;
    private JButton btnVerDetalles;
    private JTable tableFacturas;
    private JTable tableDetalles;
    private DefaultTableModel tableModel;
    private DefaultTableModel detalleTableModel;
    private FacturaService facturaService;
    private java.util.List<ec.edu.monster.model.Factura> facturasActuales;

    public Factura() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        setTitle("Consulta de facturas");
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setSize(900, 600);
        setLocationRelativeTo(null);

        facturaService = new FacturaService();

        JPanel root = new JPanel(new BorderLayout(10, 10));
        root.setBorder(BorderFactory.createEmptyBorder(15, 20, 15, 20));
        root.setBackground(new Color(20, 25, 35));
        setContentPane(root);

        JPanel topPanel = new JPanel();
        topPanel.setLayout(new BoxLayout(topPanel, BoxLayout.Y_AXIS));
        topPanel.setBackground(new Color(20, 25, 35));

        JLabel lblTitulo = new JLabel("Consulta de facturas");
        lblTitulo.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 24));
        lblTitulo.setForeground(Color.WHITE);

        JLabel lblSub = new JLabel("Ingrese la cédula del cliente para listar sus facturas.");
        lblSub.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 14));
        lblSub.setForeground(new Color(180, 190, 205));

        JPanel searchPanel = new JPanel(new FlowLayout(FlowLayout.LEFT));
        searchPanel.setBackground(new Color(20, 25, 35));

        JLabel lblCedula = new JLabel("Cédula:");
        lblCedula.setForeground(Color.WHITE);

        txtCedula = new JTextField(15);
        btnBuscar = new JButton("Buscar");
        btnVerDetalles = new JButton("Ver detalles");

        searchPanel.add(lblCedula);
        searchPanel.add(txtCedula);
        searchPanel.add(btnBuscar);
        searchPanel.add(btnVerDetalles);

        JPanel menuButtonPanel = new JPanel(new FlowLayout(FlowLayout.RIGHT));
        menuButtonPanel.setBackground(new Color(20, 25, 35));
        JButton btnVolverMenu = new JButton("VOLVER AL MENÚ");
        menuButtonPanel.add(btnVolverMenu);

        topPanel.add(lblTitulo);
        topPanel.add(Box.createVerticalStrut(5));
        topPanel.add(lblSub);
        topPanel.add(Box.createVerticalStrut(10));
        topPanel.add(searchPanel);
        topPanel.add(Box.createVerticalStrut(5));
        topPanel.add(menuButtonPanel);

        root.add(topPanel, BorderLayout.NORTH);

        String[] columnNames = {"Fecha", "Forma pago", "Subtotal", "Descuento", "Total", "Estado"};
        tableModel = new DefaultTableModel(columnNames, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        tableFacturas = new JTable(tableModel);
        tableFacturas.setFillsViewportHeight(true);

        String[] detalleColumns = {"Producto", "Cantidad", "Precio", "Subtotal"};
        detalleTableModel = new DefaultTableModel(detalleColumns, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        tableDetalles = new JTable(detalleTableModel);
        tableDetalles.setFillsViewportHeight(true);

        JPanel centerPanel = new JPanel();
        centerPanel.setLayout(new BoxLayout(centerPanel, BoxLayout.Y_AXIS));
        centerPanel.setBackground(new Color(20, 25, 35));

        JScrollPane scrollFacturas = new JScrollPane(tableFacturas);
        JScrollPane scrollDetalles = new JScrollPane(tableDetalles);

        JLabel lblDetalleTitulo = new JLabel("Detalle de la factura seleccionada");
        lblDetalleTitulo.setForeground(Color.WHITE);
        lblDetalleTitulo.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 16));

        centerPanel.add(scrollFacturas);
        centerPanel.add(Box.createVerticalStrut(10));
        centerPanel.add(lblDetalleTitulo);
        centerPanel.add(Box.createVerticalStrut(5));
        centerPanel.add(scrollDetalles);

        root.add(centerPanel, BorderLayout.CENTER);

        btnBuscar.addActionListener(e -> buscarFacturas());
        btnVerDetalles.addActionListener(e -> verDetallesFactura());
        btnVolverMenu.addActionListener(e -> {
            new userMenu().setVisible(true);
            dispose();
        });
    }// </editor-fold>//GEN-END:initComponents

    private void buscarFacturas() {
        String cedula = txtCedula.getText().trim();
        if (cedula.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese la cédula del cliente", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            facturasActuales = facturaService.listarFacturasPorCedula(cedula);

            tableModel.setRowCount(0);
            detalleTableModel.setRowCount(0);

            if (facturasActuales == null || facturasActuales.isEmpty()) {
                JOptionPane.showMessageDialog(this, "No se encontraron facturas para la cédula proporcionada", "Información", JOptionPane.INFORMATION_MESSAGE);
                return;
            }

            for (ec.edu.monster.model.Factura f : facturasActuales) {
                String fecha = f.getFecha();
                String formaPago = f.getFormaPago();
                String subtotal = f.getSubtotal() != null ? f.getSubtotal().toPlainString() : "0.00";
                String descuento = f.getDescuento() != null ? f.getDescuento().toPlainString() : "0.00";
                String total = f.getTotal() != null ? f.getTotal().toPlainString() : "0.00";
                String estado = f.getEstado();

                tableModel.addRow(new Object[]{fecha, formaPago, subtotal, descuento, total, estado});
            }

        } catch (IOException | ParseException ex) {
            logger.log(java.util.logging.Level.SEVERE, "Error al listar facturas", ex);
            JOptionPane.showMessageDialog(this, "Error al consultar facturas: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void verDetallesFactura() {
        int selectedRow = tableFacturas.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Seleccione una factura de la tabla", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (facturasActuales == null || facturasActuales.isEmpty()) {
            JOptionPane.showMessageDialog(this, "No hay facturas cargadas", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }

        ec.edu.monster.model.Factura facturaSeleccionada = facturasActuales.get(selectedRow);
        Integer idFactura = facturaSeleccionada.getId();
        if (idFactura == null) {
            JOptionPane.showMessageDialog(this, "La factura seleccionada no tiene un ID válido", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        try {
            java.util.List<ec.edu.monster.model.DetalleFactura> detalles = facturaService.listarDetallesPorFactura(idFactura);
            detalleTableModel.setRowCount(0);

            if (detalles == null || detalles.isEmpty()) {
                JOptionPane.showMessageDialog(this, "La factura seleccionada no tiene detalles", "Información", JOptionPane.INFORMATION_MESSAGE);
                return;
            }

            for (ec.edu.monster.model.DetalleFactura d : detalles) {
                String producto = d.getNombreElectrodomestico();
                String cantidad = d.getCantidad() != null ? d.getCantidad().toString() : "0";
                String precio = d.getPrecioUnitario() != null ? d.getPrecioUnitario().toPlainString() : "0.00";
                String subtotalLinea = d.getSubtotal() != null ? d.getSubtotal().toPlainString() : "0.00";

                detalleTableModel.addRow(new Object[]{producto, cantidad, precio, subtotalLinea});
            }

        } catch (IOException | ParseException ex) {
            logger.log(java.util.logging.Level.SEVERE, "Error al obtener detalle de factura", ex);
            JOptionPane.showMessageDialog(this, "Error al obtener detalle de la factura: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Factura().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
